import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '~/components/theme-provider';
import './globals.css';
import Header from '~/components/ui/header';
import { Toaster } from '~/components/ui/toaster';
import ReduxProvider from '~/redux/redux-provider';
import { cookies } from 'next/headers';
import AppProvider from '~/app/app-provider';
import SlideSession from '~/components/slide-session';

const inter = Inter({
  subsets: ['vietnamese']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <ReduxProvider>
            <Header />
            <AppProvider initialSessionToken={sessionToken?.value}>
              {children}
              <SlideSession />
            </AppProvider>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
